name: Bundle Findbar JS Files

on:
  workflow_dispatch:

jobs:
  bundle-js:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install --save-dev rollup @rollup/plugin-node-resolve @rollup/plugin-commonjs
    
    - name: Replace actor paths in all source files
      run: |
        find findbar-ai -type f \( -name '*.js' -o -name '*.mjs' \) -exec sed -i 's|chrome://userscripts/content/custom/findbar-ai/actors|chrome://userscripts/content/findbar-ai/actors|g' {} +
    
    - name: Create Rollup Configuration
      run: |
        echo "import resolve from '@rollup/plugin-node-resolve';
        import commonjs from '@rollup/plugin-commonjs';

        export default {
          input: 'findbar-ai/findbar-ai.uc.js',
          output: [
            {
              file: 'dist/findbar-ai.uc.js',
              format: 'umd',
              name: 'FindbarAI'
            }
          ],
          plugins: [
            resolve(),
            commonjs()
          ]
        }" > rollup.config.js
    
    - name: Bundle JavaScript
      run: |
        npx rollup -c --bundleConfigAsCjs

    - name: Copy actor files into dist
      run: |
        mkdir -p dist/findbar-ai/actors
        cp findbar-ai/actors/FindbarAIWindowManagerChild.sys.mjs dist/findbar-ai/actors/
        cp findbar-ai/actors/FindbarAIWindowManagerParent.sys.mjs dist/findbar-ai/actors/
    
    - name: Upload bundled file and actors
      uses: actions/upload-artifact@v4
      with:
        name: bundled-js
        path: |
          dist/findbar-ai.uc.js
          dist/findbar-ai/actors/FindbarAIWindowManagerChild.sys.mjs
          dist/findbar-ai/actors/FindbarAIWindowManagerParent.sys.mjs
