name: Update theme.json and Format

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  update_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Grant read permissions
        run: find . -name "theme.json" -print0 | xargs -0 chmod a+r

      - name: Update theme.json
        id: update_theme
        run: |
          python <<EOF
          import os
          import json
          import subprocess
          from pathlib import Path

          def get_last_modified_date(directory):
              result = subprocess.run(['stat', '-c', '%y', directory], capture_output=True, text=True)
              return result.stdout.split(' ')[0]

          def normalize_json(data):
              return json.dumps(data, indent=2, separators=(',', ': '), ensure_ascii=False)

          def update_theme_json(file_path):
              try:
                  with open(file_path, 'r', encoding='utf-8') as f:
                      original_data = json.load(f)

                  directory = os.path.dirname(file_path)
                  last_modified = get_last_modified_date(directory)

                  if original_data.get('updatedAt') == last_modified:
                      print(f"Unchanged {file_path}")
                      return False

                  updated_data = dict(original_data)
                  updated_data['updatedAt'] = last_modified

                  original_json = normalize_json(original_data)
                  updated_json = normalize_json(updated_data)

                  if original_json == updated_json:
                      print(f"Unchanged {file_path}")
                      return False

                  with open(file_path, 'w', encoding='utf-8') as f:
                      f.write(updated_json + '\n')

                  print(f"Updated {file_path} with date {last_modified}")
                  return True

              except Exception as e:
                  print(f"Error processing {file_path}: {e}")
                  return False

          files = subprocess.run(['find', '.', '-name', 'theme.json', '-print0'], capture_output=True, text=True).stdout.split('\0')
          updated = False
          for file in filter(None, files):
              if update_theme_json(file):
                  updated = True

          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              f.write(f"updated={'true' if updated else 'false'}\n")
          EOF

      - name: Commit theme.json changes
        if: steps.update_theme.outputs.updated == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update theme.json"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install Prettier
        run: npm install --save-dev prettier

      - name: Add node_modules to path
        run: echo "::add-path::./node_modules/.bin"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Run Prettier
        run: prettier --write .

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Auto format"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

